spring.application.name=microservicio-seguridad
server.port=8081

# ----- Base de datos H2 (modo archivo, persiste entre reinicios) -----
spring.datasource.url=jdbc:h2:file:./datos/seguridaddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2 -> http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ----- Configuracion JWT -----
# La clave debe ser Base64 y decodificar a minimo 32 bytes (256 bits)
app.jwt.secreto=Y29kZWFydGlTZWNyZXRvU3VwZXJTZWd1cm9QYXJhSldUMjAyNkNvbkNsYXZlTGFyZ2E=
app.jwt.expiracion=86400000